# Generated by Django 5.0.12 on 2025-03-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Art",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("series", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="default.png", null=True, upload_to=""
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
