# Generated by Django 5.0.12 on 2025-03-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Art",
        ),
    ]
